### ISSUE TITLE
AWS-0.0.0.0 -  EC2 Instance Connect (browser-based SSH connection) fails

### ISSUE THREAD

**Issue by EtricKombat** [EtricKombat/AWS#1]
EC2 Instance Connect (browser-based SSH connection) fails...WHY?!

**Comment by EtricKombat** [comment]
### Related Official Article

        https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-set-up.html

**Comment by EtricKombat** [comment]
Issue got resolved after trying out the steps mentioned in above listed article (or by its own)

**Comment by Teenasusanvarghese** [comment]
I had same issue & mine got resolved by trying to change all the rules as "anywhere"
