### ISSUE TITLE
AWS-RDS-0.0.0.3 : psql: could not connect to server: Connection timed out Is the server running on host

### ISSUE THREAD

**Issue by Teenasusanvarghese** [EtricKombat/AWS#4]
# Error :
While trying to connect to a postgres RDS from an EC2 getting the listed error : 

        [ec2-user@ip-172-51-46-13 ~]$ psql -h rds-tta-ec2.cjdsbrim0exc.ap-southeast-1.                                                                                        
        rds.amazonaws.com -p 5432 -U postgres
        psql: could not connect to server: Connection timed out
                Is the server running on host

Snapshot:

![image](https://user-images.githubusercontent.com/54981984/91213125-c6eaa600-e72e-11ea-9a2f-fd6d625caaac.png)

**Comment by Teenasusanvarghese** [comment]
# Solution 

EC2's SG should enable RDS IP /PORT (INBOUND)
RDS SG should enable ECS private IP/PORT(INBOUND)

Ref : https://serverfault.com/questions/656079/unable-to-connect-to-public-postgresql-rds-instance

**Comment by EtricKombat** [comment]
# AWS EC2 to RDS (mariaDB) connection

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/mAaWIF7mzcY/0.jpg)](https://www.youtube.com/watch?v=mAaWIF7mzcY)
